name: Build Image
on:
  push:
    tags:
      - '*-v*.*.*'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set tag output
        id: tag
        run: |
          TAG=${GITHUB_REF#refs/*/}"

          APP=$(echo $TAG | cut -d'-' -f1)
          VERSION=$(echo $TAG | cut -d'-' -f2)
          APP_VERSION=$(grep -Eo "FROM[^:]+:[^[:space:]]+" ${APP}/Dockerfile | cut -d ":" -f 2-)
          APP_IMAGE=$(grep -Eo "FROM[^:]+:[^[:space:]]+" superset/Dockerfile | cut -d ":" -f -1 | cut -d " " -f 2-)


          echo "app=${APP}" >> $GITHUB_OUTPUT
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "app_version=${APP_VERSION}" >> $GITHUB_OUTPUT
          echo "app_image=${APP_IMAGE}" >> $GITHUB_OUTPUT
      - name: Test
        run: |
          echo "App: ${{ steps.tag.outputs.app }}"
          echo "Version: ${{ steps.tag.outputs.version }}"
          echo "App Version: ${{ steps.tag.outputs.app_version }}"
          echo "App Image: ${{ steps.tag.outputs.app_image }}"
      # - name: Build and push
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     push: true
      #     tags: |
      #       ghcr.io/${{ github.repository }}:${{ github.ref }}
      #       ghcr.io/${{ github.repository }}:latest
