name: Build Image
on:
  push:
    tags:
      - '*-v*.*.*'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: |
          echo ${{ github.ref }}
      # - name: Build and push
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     push: true
      #     tags: |
      #       ghcr.io/${{ github.repository }}:${{ github.ref }}
      #       ghcr.io/${{ github.repository }}:latest
